### ISSUE TITLE
Self test error reference

### ISSUE THREAD

**Issue by martykan** [Sensirion/embedded-i2c-scd4x#2]
Hello, is there a table of the error codes returned by perform_self_test? We're getting error 268

**Comment by rnestler** [comment]
Hi @martykan 

I just checked the datasheet at https://www.sensirion.com/scd4x/ but couldn't find documentation for the error codes there. I'd advice you to contact product support under https://www.sensirion.com/en/about-us/support-center/ so they can help you diagnosing the issue.
