### ISSUE TITLE
Implementing this on 'embedded-common' library.

### ISSUE THREAD

**Issue by PopherTheG** [Sensirion/embedded-i2c-scd4x#3]
I have been using the https://github.com/Sensirion/embedded-common for other sensors (SGP40 and SHT, and SPS30) and the 'embedded-common' used here is not the same as the other drivers. Can you help me integrate this sensor using '[embedded-common](https://github.com/Sensirion/embedded-common)' library?

**Comment by rnestler** [comment]
This driver uses the embedded-common from the `driver-generator/main` branch: https://github.com/Sensirion/embedded-common/tree/driver-generator/main.

The https://github.com/Sensirion/embedded-i2c-sgp40 uses the same.

The differences between the two embedded-common branches aren't that big, but there was quite some restructuring and renaming that happened.

**Comment by PopherTheG** [comment]
@rnestler for production use should the `driver-generator/main` branch should be used? So I will adjust the driver file for `sps30`.

**Comment by rnestler** [comment]
> @rnestler for production use should the driver-generator/main branch be used?

@PopherTheG Yes and maybe it would make sense for us to just merge it into master. We moved from writing all the drivers manually to generating them form an interface description. For that we needed to alter the API to make it easier to generate code for it.
But we didn't yet update the drivers of the older products, which were written manually.

**Comment by PopherTheG** [comment]
I see. When is this merging to master expected?

**Comment by rnestler** [comment]
I'll close this, since there is a new release of embedded-common. Pull requests to update the old drivers to a new embedded-common are welcome :slightly_smiling_face: For us the old drivers have a lower priority, since most people do prototyping with the newest sensors.
