### ISSUE TITLE
How to use with "embedded-sps" library

### ISSUE THREAD

**Issue by ChangWan-Kim** [Sensirion/embedded-i2c-scd4x#6]
hello.

I'm currently developing a board that uses sps30 and scd41 together.

I downloaded the embedded library provided by Sensirion.

When I open the two libraries, I see a file with the same name, but with different contents.

Do I have to manually fix the library conflicts?

**Comment by Rol-la** [comment]
Hi Kim,

The driver repositories are structured in a way, that each driver repository is self contained and can be built by its own. This implies that some content between two driver repos is redundant. This is especially true for the framework code (all the files that start with <sensirion_>).
As our drivers and the framework evolve over time it is the case that not all drivers work with any other version of the corresponding <sensirion_> file.
When you want to use several drivers in one project you will need manually merge the contents of the two repositories:
- Decide from which repository you take the <sensirion_> files.
- Include the driver code (files with name of the sensor) of both sensors.
- Adapt the driver code such that it works with the selected framework.
- Make sure that the make file includes all sources to build.
- Create your own usage example with a main() function as application entry point.

best regards,
Rolf

**Comment by ChangWan-Kim** [comment]
Thank you for answer.

as you explained

Fixed by loading "sensirion_*" files from scd41's repository.

Changed some used function names in sps30.c file.

Examples of scd41 and sps30 worked well at the same time.

thank you

**Comment by ChangWan-Kim** [comment]
Thank you for answer.

as you explained

Fixed by loading "sensirion_*" files from scd41's repository.

Changed some used function names in sps30.c file.

Examples of scd41 and sps30 worked well at the same time.

thank you
