### ISSUE TITLE
Will be esp32c6 implementation?

### ISSUE THREAD

**Issue by sallah21** [Sensirion/embedded-i2c-scd4x#7]

**Comment by psachs** [comment]
Please use the Arduino driver with ESP32: https://github.com/Sensirion/arduino-i2c-scd4x

It should work out of the box for ESP32 variations

**Comment by sallah21** [comment]
In my project i need to send data from scd4x with matter protocol to home assistant. There is a project on github called esp32-arduino-matter, but for now it doesn't support esp32c6, so as I know i have to implement it in C code.

**Comment by sallah21** [comment]
Not working currently on this project and had to give it back to my university so currently i don't have these devices. So I will close this issue
